### ISSUE TITLE
Windows install blows away `node`and `npx` from PATH?

### ISSUE THREAD

**Issue by gregcotten** [sushichop/gha-swift-env#6]
https://github.com/videovillage/Napoli/actions/runs/3594116728/jobs/6051974565

I tried migrating from my custom "lightweight" Windows swift install step to gha-swift-env and it seems to interfere with setup-node. If I had to guess, this step may interfere with other installed executables as well.

Feel free to file this under "not my problem" :)

Greg

**Comment by sushichop** [comment]
@gregcotten 
Thanks for sharing this issue.
I'll look into it when I have a moment🙂

**Comment by sushichop** [comment]
@gregcotten 
I fixed this issue(interference with `actions/setup-node`). See #7.

And I have released [sushichop/gha-swift-env v1.0.5](https://github.com/sushichop/gha-swift-env/releases/tag/v1.0.5).
Now, you can use it by specifying `sushichop/gha-swift-env@v1`.

Cheers🎉

**Comment by sushichop** [comment]
I'm closing this issue since it was fixed by #7.
Please feel free to reopen it if you have any questions.
